const C=['Alimentação','Transporte','Moradia','Educação','Saúde','Lazer','Assinaturas','Trabalho','Investimentos','Cartão','Outros'];const $=i=>document.getElementById(i);const BRL=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const M=(d=new Date())=>d.toISOString().slice(0,7);let flow,cat,defer;const s=JSON.parse(localStorage.getItem('rfv7'))||{wallets:[],tx:[],cards:[],inv:[],goals:[],cats:C,theme:'dark',privacy:false};
function save(){localStorage.setItem('rfv7',JSON.stringify(s));render()}function cur(){return s.tx.filter(x=>x.month===M())}function totals(a=cur()){return a.reduce((o,x)=>{x.type==='income'?o.i+=x.amount:o.e+=x.amount;return o},{i:0,e:0})}function net(){return s.wallets.reduce((a,w)=>a+w.balance,0)+s.inv.reduce((a,i)=>a+i.amount,0)}function debt(){return cur().filter(x=>x.cardId).reduce((a,x)=>a+x.amount,0)}function bc(){let m={};cur().filter(x=>x.type==='expense').forEach(x=>m[x.cat]=(m[x.cat]||0)+x.amount);return m}
function render(){document.body.classList.toggle('light',s.theme==='light');document.body.classList.toggle('privacy',s.privacy);$('date').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});selects();dash();wallets();txs();cards();invest();goals();reports()}
function selects(){category.innerHTML=s.cats.map(x=>`<option>${x}</option>`).join('');walletSel.innerHTML='<option value="">Sem carteira</option>'+s.wallets.map(w=>`<option value="${w.id}">${w.name}</option>`).join('');filterWallet&&(filterWallet.innerHTML='<option value="all">Todas</option>'+s.wallets.map(w=>`<option value="${w.id}">${w.name}</option>`).join(''));parcelCard.innerHTML=s.cards.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}
function dash(){let t=totals(),bal=t.i-t.e,inv=s.inv.reduce((a,i)=>a+i.amount,0),sav=t.i?Math.round(bal/t.i*100):0,score=Math.max(0,Math.min(100,50+sav-(debt()>t.i*.5?20:0)));net.innerHTML=`<span class="money">${BRL(net())}</span>`;income.innerHTML=`<span class="money">${BRL(t.i)}</span>`;expense.innerHTML=`<span class="money">${BRL(t.e)}</span>`;debtEl=$('debt');debtEl.innerHTML=`<span class="money">${BRL(debt())}</span>`;invTotal.innerHTML=`<span class="money">${BRL(inv)}</span>`;saveRate.textContent=sav+'%';proj.innerHTML=`<span class="money">${BRL(net()+bal*12)}</span>`;scoreEl=$('score');scoreEl.textContent=score;let alerts=makeAlerts(t,bal);insight.textContent=alerts[0];$('alerts').innerHTML=alerts.map(a=>`<div class="ai">${a}</div>`).join('');walletMini.innerHTML=s.wallets.map(w=>`<div class="row"><b>${w.name}</b><span class="money">${BRL(w.balance)}</span></div>`).join('')||'<p>Nenhuma carteira.</p>';charts()}
function makeAlerts(t,bal){let a=[];if(!s.wallets.length)a.push('💼 Crie uma carteira para controlar bancos, Pix e dinheiro.');if(!t.i)a.push('💡 Cadastre sua renda mensal.');if(bal<0)a.push('⚠️ Saldo mensal negativo.');if(debt()>t.i*.5&&t.i>0)a.push('💳 Fatura do cartão acima de 50% da renda.');if(s.goals.length&&bal>0)a.push('🎯 Direcione parte do saldo para suas metas.');if(s.inv.length)a.push('📈 Investimentos incluídos no patrimônio.');return a.length?a:['✅ Finanças equilibradas neste mês.']}
function charts(){if(!window.Chart)return;let t=totals();if(flow)flow.destroy();flow=new Chart($('flow'),{type:'bar',data:{labels:['Receitas','Despesas','Cartões'],datasets:[{data:[t.i,t.e,debt()]}]}});let b=bc();if(cat)cat.destroy();cat=new Chart($('catChart'),{type:'doughnut',data:{labels:Object.keys(b),datasets:[{data:Object.values(b)}]}})}
function wallets(){walletList.innerHTML=s.wallets.map(w=>`<div class="row"><div><b>${w.name}</b><div class="tag">${w.type}</div></div><b class="money">${BRL(w.balance)}</b><button class="delete" onclick="delWallet('${w.id}')">Excluir</button></div>`).join('')||'<p>Nenhuma carteira.</p>'}
function txs(){let q=(search.value||'').toLowerCase(),f=filter.value;let a=cur().filter(x=>(f==='all'||x.type===f)&&x.desc.toLowerCase().includes(q));txList.innerHTML=a.map(x=>`<div class="row"><div><b>${x.desc}</b><div class="tag">${x.cat} • ${x.walletName||'sem carteira'} ${x.inst?'• parcela '+x.inst:''}</div></div><b class="${x.type} money">${x.type==='income'?'+':'-'} ${BRL(x.amount)}</b><button class="delete" onclick="delTx('${x.id}')">Excluir</button></div>`).join('')||'<p>Nenhuma movimentação.</p>'}
function cards(){cardList.innerHTML=s.cards.map(c=>`<div class="row"><div><b>${c.name}</b><div class="tag">Limite ${BRL(c.limit)} • vence dia ${c.due}</div></div><button class="delete" onclick="delCard('${c.id}')">Excluir</button></div>`).join('')||'<p>Nenhum cartão.</p>'}
function invest(){let total=s.inv.reduce((a,i)=>a+i.amount,0),fut=s.inv.reduce((a,i)=>a+i.amount*Math.pow(1+i.rate/100,12),0);invProjection.textContent=s.inv.length?`Projeção 12 meses: ${BRL(fut)} (hoje ${BRL(total)})`:'Cadastre investimentos.';invList.innerHTML=s.inv.map(i=>`<div class="row"><div><b>${i.name}</b><div class="tag">${i.type} • ${i.rate}% ao mês</div></div><b class="money">${BRL(i.amount)}</b><button class="delete" onclick="delInv('${i.id}')">Excluir</button></div>`).join('')||'<p>Nenhum investimento.</p>'}
function goals(){goalList.innerHTML=s.goals.map(g=>{let p=Math.min(100,Math.round(g.saved/g.target*100));return `<div class="goal"><div style="width:100%"><b>${g.name}</b><p>${BRL(g.saved)} de ${BRL(g.target)} • ${p}%</p><div class="progress"><span style="width:${p}%"></span></div></div><button class="delete" onclick="delGoal('${g.id}')">Excluir</button></div>`}).join('')||'<p>Nenhuma meta.</p>'}
function reports(){let m={};s.tx.forEach(x=>{m[x.month]??={i:0,e:0};x.type==='income'?m[x.month].i+=x.amount:m[x.month].e+=x.amount});summary.innerHTML=Object.entries(m).sort().reverse().map(([k,v])=>`<div class="row"><b>${k}</b><span class="money">Receitas ${BRL(v.i)} • Despesas ${BRL(v.e)} • Saldo ${BRL(v.i-v.e)}</span></div>`).join('')||'<p>Sem relatórios.</p>'}
window.delWallet=id=>{s.wallets=s.wallets.filter(x=>x.id!==id);save()};window.delTx=id=>{s.tx=s.tx.filter(x=>x.id!==id);save()};window.delCard=id=>{s.cards=s.cards.filter(x=>x.id!==id);save()};window.delInv=id=>{s.inv=s.inv.filter(x=>x.id!==id);save()};window.delGoal=id=>{s.goals=s.goals.filter(x=>x.id!==id);save()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('on'));b.classList.add('on');$(b.dataset.p).classList.add('on');title.textContent=b.textContent});
walletForm.onsubmit=e=>{e.preventDefault();s.wallets.push({id:crypto.randomUUID(),name:walletName.value,type:walletType.value,balance:Number(walletBalance.value||0)});walletForm.reset();save()}
txForm.onsubmit=e=>{e.preventDefault();let w=s.wallets.find(x=>x.id===walletSel.value),amt=Number(amount.value);s.tx.push({id:crypto.randomUUID(),desc:desc.value,amount:amt,type:type.value,cat:category.value,walletId:w?.id,walletName:w?.name,recurring:recurring.checked,date:new Date().toISOString(),month:M()});if(w)w.balance+=type.value==='income'?amt:-amt;txForm.reset();save()}
cardForm.onsubmit=e=>{e.preventDefault();s.cards.push({id:crypto.randomUUID(),name:cardName.value,limit:Number(cardLimit.value||0),due:cardDue.value});cardForm.reset();save()}
parcelForm.onsubmit=e=>{e.preventDefault();let total=Number(parcelAmount.value),n=Number(parcelCount.value),c=s.cards.find(x=>x.id===parcelCard.value),part=total/n;for(let i=0;i<n;i++){let d=new Date();d.setMonth(d.getMonth()+i);s.tx.push({id:crypto.randomUUID(),desc:parcelDesc.value,amount:part,type:'expense',cat:'Cartão',cardId:c?.id,cardName:c?.name,inst:`${i+1}/${n}`,date:new Date().toISOString(),month:M(d)})}parcelForm.reset();save()}
invForm.onsubmit=e=>{e.preventDefault();s.inv.push({id:crypto.randomUUID(),name:invName.value,type:invType.value,amount:Number(invAmount.value||0),rate:Number(invRate.value||0)});invForm.reset();save()}
goalForm.onsubmit=e=>{e.preventDefault();s.goals.push({id:crypto.randomUUID(),name:goalName.value,target:Number(goalTarget.value||0),saved:Number(goalSaved.value||0)});goalForm.reset();save()}
simGoal.onclick=()=>{let g=s.goals[0],v=Number(monthlySave.value);goalSim.textContent=g&&v>0?`Guardando ${BRL(v)}/mês, você alcança "${g.name}" em ${Math.ceil((g.target-g.saved)/v)} mês(es).`:'Crie uma meta e informe valor.'}
plan.onclick=()=>{let t=totals(),bal=t.i-t.e;planText.innerHTML=`<div class="ai"><b>Plano do mês</b><p>1. Pague despesas essenciais.<br>2. Separe ${BRL(Math.max(0,bal*.3))} para metas/investimentos.<br>3. Revise cartão: ${BRL(debt())}.<br>4. Mantenha economia acima de 20%.</p></div>`}
theme.onclick=()=>{s.theme=s.theme==='dark'?'light':'dark';save()};search.oninput=txs;filter.onchange=txs;sample.onclick=()=>{s.wallets.push({id:crypto.randomUUID(),name:'Nubank',type:'Banco',balance:1200});s.tx.push({id:crypto.randomUUID(),desc:'Salário',amount:1800,type:'income',cat:'Trabalho',date:new Date().toISOString(),month:M()},{id:crypto.randomUUID(),desc:'Mercado',amount:430,type:'expense',cat:'Alimentação',date:new Date().toISOString(),month:M()});save()}
function down(n,c,t){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:t}));a.download=n;a.click()}csv.onclick=()=>{let r=['Data,Mes,Tipo,Categoria,Descricao,Valor,Carteira,Cartao'];s.tx.forEach(x=>r.push(`${x.date},${x.month},${x.type},${x.cat},"${x.desc}",${x.amount},${x.walletName||''},${x.cardName||''}`));down('ramalho-finance-v7.csv',r.join('\n'),'text/csv')};backup.onclick=()=>down('ramalho-finance-v7-backup.json',JSON.stringify(s,null,2),'application/json');restore.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{Object.assign(s,JSON.parse(r.result));save()};r.readAsText(f)};print.onclick=()=>window.print();clear.onclick=()=>{if(confirm('Apagar tudo?')){localStorage.removeItem('rfv7');location.reload()}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();defer=e});install.onclick=()=>defer?defer.prompt():alert('Use o menu do navegador e escolha Instalar aplicativo.');
function bg(){let c=$('bg'),x=c.getContext('2d'),w,h,p;function rz(){w=c.width=innerWidth;h=c.height=innerHeight;p=Array.from({length:Math.min(100,Math.floor(w*h/14000))},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.6,vy:(Math.random()-.5)*.6}))}function loop(){x.clearRect(0,0,w,h);x.fillStyle='rgba(34,211,238,.7)';p.forEach(a=>{a.x+=a.vx;a.y+=a.vy;if(a.x<0||a.x>w)a.vx*=-1;if(a.y<0||a.y>h)a.vy*=-1;x.beginPath();x.arc(a.x,a.y,1.4,0,7);x.fill()});x.strokeStyle='rgba(34,211,238,.11)';for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++){let dx=p[i].x-p[j].x,dy=p[i].y-p[j].y;if(dx*dx+dy*dy<9000){x.beginPath();x.moveTo(p[i].x,p[i].y);x.lineTo(p[j].x,p[j].y);x.stroke()}}requestAnimationFrame(loop)}rz();addEventListener('resize',rz);loop()}bg();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');
